source "https://rubygems.org"

gem "rails", "~> 5.0.0", ">= 5.0.0.1"
gem "mysql2", "~> 0.4.2"
gem "puma", "~> 3.0"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.2"
gem "jquery-rails"
gem "turbolinks", "~> 5"
gem "jbuilder", "~> 2.5"
gem "bcrypt"
gem "bootstrap-sass"
gem "cancancan"
gem "ransack"
gem "kaminari"
gem "public_activity"
gem "ckeditor"
gem "font-awesome-rails"
gem "omniauth"
gem "omniauth-facebook"
gem "omniauth-google-oauth2"
gem "omniauth-twitter", "1.2.0"
gem "config"
gem "carrierwave"
gem "mini_magick"
gem "fog", "1.36.0"
gem "devise"
gem "simple_form"

group :development, :test do
  gem "byebug", platform: :mri
  gem "pry"
  gem "fabrication"
  gem "rspec-rails"
  gem "web-console"
  gem "spring"
  gem "faker"
  gem "letter_opener"
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "listen", "~> 3.0.5"
end
